TO_CSS_NAME = {
    "animation": "animation",
    "animationDuration": "animation-duration",
    "animationTimingFunction": "animation-timing-function",
    "animationDelay": "animation-delay",
    "animationIterationCount": "animation-iteration-count",
    "animationDirection": "animation-direction",
    "animationFillMode": "animation-fill-mode",
    "animationPlayState": "animation-play-state",
    "alignContent": "align-content",
    "alignItems": "align-items",
    "alignSelf": "align-self",
    "aria": "aria",
    "aspectRatio": "aspect-ratio",
    "backgroundClip": "background-clip",
    "backgroundImage": "background-image",
    "backgroundPosition": "background-position",
    "backgroundRepeat": "background-repeat",
    "backgroundSize": "background-size",
    "borderCollapse": "border-collapse",
    "borderRadius": "border-radius",
    "borderStyle": "border-style",
    "borderWidth": "border-width",
    "boxDecorationBreak": "box-decoration-break",
    "boxSizing": "box-sizing",
    "boxShadow": "box-shadow",
    "brightness": "brightness",
    "colors": "color",
    "columns": "columns",
    "container": "container",
    "content": "content",
    "contrast": "contrast",
    "cursor": "cursor",
    "clear": "clear",
    "dropShadow": "drop-shadow",
    "fill": "fill",
    "flex": "flex",
    "flexBasis": "flex-basis",
    "flexDirection": "flex-direction",
    "flexGrow": "flex-grow",
    "flexShrink": "flex-shrink",
    "flexWrap": "flex-wrap",
    "float": "float",
    "fontFamily": "font-family",
    "fontSize": "font-size",
    "fontWeight": "font-weight",
    "fontStyle": "font-style",
    "fontVariantNumeric": "font-variant-numeric",
    "fromPosition": "--tw-gradient-from-position",
    "gradientColorStopPositions": "gradient-color-stop-positions",
    "grayscale": "grayscale",
    "gridAutoColumns": "grid-auto-columns",
    "gridAutoRows": "grid-auto-rows",
    "isolation": "isolation",
    "justifyContent": "justify-content",
    "justifyItems": "justify-items",
    "justifySelf": "justify-self",
    "gridColumn": "grid-column",
    "gridColumnEnd": "grid-column-end",
    "gridColumnStart": "grid-column-start",
    "gridRow": "grid-row",
    "gridRowEnd": "grid-row-end",
    "gridRowStart": "grid-row-start",
    "gridTemplateColumns": "grid-template-columns",
    "gridTemplateRows": "grid-template-rows",
    "height": "height",
    "hueRotate": "hue-rotate",
    "inset": "inset",
    "invert": "invert",
    "keyframes": "keyframes",
    "leading": "line-height",
    "letterSpacing": "letter-spacing",
    "lineHeight": "line-height",
    "listStyleType": "list-style-type",
    "listStyleImage": "list-style-image",
    "margin": "margin",
    "marginRight": "margin-right",
    "marginLeft": "margin-left",
    "marginTop": "margin-top",
    "marginBottom": "margin-bottom",
    "lineClamp": "line-clamp",
    "maxHeight": "max-height",
    "maxWidth": "max-width",
    "marginLeftRight": "margin-left",
    "marginTopBottom": "margin-top",
    "mixBlendMode": "mix-blend-mode",
    "minHeight": "min-height",
    "minWidth": "min-width",
    "objectFit": "object-fit",
    "objectPosition": "object-position",
    "opacity": "opacity",
    "order": "order",
    "overscrollBehavior": "overscroll-behavior",
    "outlineOffset": "outline-offset",
    "outlineWidth": "outline-width",
    "paddingTop": "padding-top",
    "paddingBottom": "padding-bottom",
    "paddingRight": "padding-right",
    "paddingLeft": "padding-left",
    "placeContent": "place-content",
    "placeItems": "place-items",
    "placeSelf": "place-self",
    "ringColor": "ring-color",
    "ringOffsetWidth": "ring-offset-width",
    "ringOpacity": "ring-opacity",
    "ringWidth": "ring-width",
    "rotate": "rotate",
    "saturate": "saturate",
    "scale": "scale",
    "screens": "screens",
    "sepia": "sepia",
    "skew": "skew",
    "spacing": "spacing",
    "stroke": "stroke",
    "strokeWidth": "stroke-width",
    "supports": "supports",
    "data": "data",
    "tableLayout": "table-layout",
    "toPosition": "--tw-gradient-to-position",
    "to": "--tw-gradient-to",
    "textAlign": "text-align",
    "textDecorationThickness": "text-decoration-thickness",
    "textUnderlineOffset": "text-underline-offset",
    "textTransform": "text-transform",
    "textWrap": "text-wrap",
    "transform": "transform",
    "transformOrigin": "transform-origin",
    "transitionDelay": "transition-delay",
    "transitionDuration": "transition-duration",
    "transitionProperty": "transition-property",
    "transitionTimingFunction": "transition-timing-function",
    "translate": "translate",
    "verticalAlign": "vertical-align",
    "size": "size",
    "viaPosition": "--tw-gradient-via-position",
    "width": "width",
    "willChange": "will-change",
    "zIndex": "z-index",
    "backgroundColor": "background-color",
    "backgroundOpacity": "background-opacity",
    "borderColor": "border-color",
    "borderOpacity": "border-opacity",
    "borderSpacing": "border-spacing",
    "boxShadowColor": "box-shadow-color",
    "caretColor": "caret-color",
    "divideColor": "divide-color",
    "divideOpacity": "divide-opacity",
    "divideStyle": "divide-style",
    "divideWidth": "divide-width",
    "gap": "gap",
    "gradientColorStops": "gradient-color-stops",
    "outlineColor": "outline-color",
    "padding": "padding",
    "paddingLeftRight": "padding-left",
    "paddingTopBottom": "padding-top",
    "placeholderColor": "placeholder-color",
    "placeholderOpacity": "placeholder-opacity",
    "ringOffsetColor": "ring-offset-color",
    "scrollMargin": "scroll-margin",
    "scrollPadding": "scroll-padding",
    "space": "space",
    "textColor": "color",
    "textDecorationColor": "text-decoration-color",
    "textIndent": "text-indent",
    "textOpacity": "text-opacity",
    "textDecoration": "text-decoration",
}
TO_TAILWIND_NAME = {
    "alignContent": "content",
    "alignItems": "items",
    "alignSelf": "self",
    "animationNames": "animate",
    "animationTimingFunction": ["animate", "animation-timing-function"],
    "animationIterationCount": ["animate", "animation-direction"],
    "animationDirection": ["animate", "animation-direction"],
    "animationFillMode": ["animate", "animation-fill"],
    "animationPlayState": ["animate", "animation-play-state"],
    "aria": "aria",
    "aspectRatio": "aspect",
    "backgroundClip": "bg-clip",
    "backgroundImage": "bg",
    "backgroundPosition": "bg",
    "backgroundRepeat": "bg",
    "backgroundSize": "bg",
    "borderCollapse": "border",
    "borderRadius": "rounded",
    "borderStyle": "border",
    "borderWidth": "border",
    "boxDecorationBreak": "box-decoration",
    "boxSizing": "box",
    "boxShadow": "shadow",
    "brightness": "brightness",
    "colors": "colors",
    "columns": "columns",
    "container": "container",
    "content": "content",
    "clear": "clear",
    "contrast": "contrast",
    "cursor": "cursor",
    "display": [
        "block",
        "inline",
        "inline-block",
        "flex",
        "inline-flex",
        "grid",
        "inline-grid",
        "table",
        "inline-table",
        "table-row",
        "table-cell",
        "none",
        "hidden"
    ],
    "from": "from",
    "fromPosition": "from",
    "fill": "fill",
    "flex": "flex",
    "flexBasis": "basis",
    "flexDirection": "flex",
    "flexGrow": ["grow", "flex-grow"],
    "flexShrink": ["shrink", "flex-shrink"],
    "flexWrap": "flex",
    "float": "float",
    "fontSmoothing": ["antialiased", "subpixel-antialiased"],
    "filter": [
        "blur",
        "brightness",
        "contrast",
        "drop-shadow",
        "grayscale",
        "hue-rotate",
        "invert",
        "saturate",
        "sepia"
    ],
    "backdrop-filter": ["backdrop"],
    "fontFamily": "font",
    "fontSize": "text",
    "fontWeight": "font",
    "fontStyle": [
        'italic',
        "not-italic",
    ],
    "fontVariantNumeric": [
        "normal-nums",
        "ordinal",
        "slashed-zero",
        "lining-nums",
        "oldstyle-nums",
        "proportional-nums",
        "tabular-nums",
        "diagonal-fractions",
        "stacked-fractions",
    ],
    "gradientColorStopPositions": "gradient",
    "grayscale": "grayscale",
    "gridAutoColumns": "auto-cols",
    "gridAutoRows": "auto-rows",
    "isolation": ["isolation", "isolate"],
    "justifyContent": "justify",
    "justifyItems": "justify-items",
    "justifySelf": "justify-self",
    "gridColumn": "col",
    "gridColumnEnd": "col-end",
    "gridColumnStart": "col-start",
    "gridRow": "row",
    "gridRowEnd": "row-end",
    "gridRowStart": "row-start",
    "gridTemplateColumns": "grid-cols",
    "gridTemplateRows": "grid-rows",
    "height": "h",
    "hueRotate": "hue-rotate",
    "inset": "inset",
    "invert": "invert",
    "keyframes": "keyframes",
    "leading": "leading",
    "letterSpacing": "tracking",
    "lineHeight": "leading",
    "listStyleType": "list",
    "listStyleImage": "list",
    "margin": "m",
    "marginLeft": ["ml", "space-x"],
    "marginRight": "mr",
    "marginTop": ["mt", 'space-y'],
    "marginBottom": "mb",
    "lineClamp": "line-clamp",
    "maxHeight": "max-h",
    "maxWidth": "max-w",
    "minHeight": "min-h",
    "minWidth": "min-w",
    "marginLeftRight": "mx",
    "marginTopBottom": "my",
    "mixBlendMode": "mix-blend",
    "objectFit": "object",
    "objectPosition": "object",
    "opacity": "opacity",
    "order": "order",
    "overscrollBehavior": "overscroll",
    "outlineOffset": "outline-offset",
    "outlineWidth": "outline",
    "position": [
        "static",
        "relative",
        "absolute",
        "fixed",
        "sticky"
    ],
    "placeContent": "place-content",
    "placeItems": "place-items",
    "placeSelf": "place-self",
    "ringColor": "ring",
    "ringOffsetWidth": "ring-offset",
    "ringOpacity": "ring-opacity",
    "ringWidth": "ring",
    "rotate": "rotate",
    "saturate": "saturate",
    "scale": "scale",
    "screens": "screens",
    "sepia": "sepia",
    "skew": "skew",
    "srOnly": "sr-only",
    "stroke": "stroke",
    "strokeWidth": "stroke",
    "supports": "supports",
    "data": "data",
    "tableLayout": "table",
    "to": "to",
    "toPosition": "to",
    "textAlign": "text",
    "textDecorationThickness": "decoration",
    "textUnderlineOffset": "underline-offset",
    "textTransform": [
        "uppercase",
        "lowercase",
        "capitalize",
        "normal-case",
    ],
    "textWrap": "text",
    "transform": "transform",
    "transformOrigin": "origin",
    "transitionDelay": "delay",
    "transitionDuration": "duration",
    "transitionProperty": "transition",
    "transitionTimingFunction": "ease",
    "translate": "translate",
    "verticalAlign": "align",
    "via": "via",
    "viaPosition": "via",
    "size": "size",
    "width": "w",
    "willChange": "will-change",
    "zIndex": "z",

    "backgroundColor": "bg",
    "backgroundOpacity": "bg-opacity",
    "borderColor": "border",
    "borderOpacity": "border-opacity",
    "borderSpacing": "border-spacing",
    "boxShadowColor": "shadow",
    "caretColor": "caret",
    "divideColor": "divide",
    "divideOpacity": "divide-opacity",
    "divideStyle": "divide",
    "divideWidth": "divide",
    "gap": "gap",
    "gradientColorStops": "gradient",
    "outlineColor": "outline",
    "overflow": "overflow",
    "padding": "p",
    "paddingLeft": "pl",
    "paddingRight": "pr",
    "paddingTop": "pt",
    "paddingBottom": "pb",
    "paddingLeftRight": "px",
    "paddingTopBottom": "py",
    "placeholderColor": "placeholder",
    "placeholderOpacity": "placeholder-opacity",
    "ringOffsetColor": "ring-offset",
    "scrollMargin": "scroll-m",
    "scrollPadding": "scroll-p",
    "space": "space",
    "textColor": "text",
    "textDecorationColor": "decoration",
    "textIndent": "indent",
    "textOpacity": "text-opacity",
    "textDecoration": [
        "none",  # No decoration
        "underline",  # Underline
        "overline",  # Overline
        "line-through",  # Line through
        "blink",  # Blink (not widely supported),
    ]
}
